apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "joal-controller.fullname" . }}
  labels:
    {{- include "joal-controller.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "joal-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "joal-controller.labels" . | nindent 8 }}
    spec:
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      securityContext:
        {{ toYaml .Values.podSecurityContext | indent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
        - name: {{ template "joal-controller.name" . }}-registry-key
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ template "joal-controller.name" . }}-sa
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
